### ISSUE TITLE
ORF obsahuje více verzí rozpočtu?

### ISSUE THREAD

**Issue by kluchLProconom** [KoncepceBIM/ORF#2]
https://github.com/KoncepceBIM/ORF/blob/b610b14ea32c57c1fa76437bcaf8431c98aaca31/ORF.XML/Schema/ORF_v0.1.xsd#L246

Nebylo by to možná od věci - dodatečné info při VŘ, více variant k ocenění

**Comment by callidasw** [comment]
Nevím jestli Vaší otázku správně chápu.. podle stávající verze schematu je multiplicita elementu "Rozpocet" nastavena na 1.. z toho odvozuji, že v jedné instanci dokumentu má být přenášena jedna verze rozpočtu.

Pokud máte na mysli atribut "Verze" u kořenového elementu "ORF", ten je nejspíš určen pro rozlišení verze strukutry dokumentu.. aby byla šance v cílových systémech reagovat na různé vývojové etapy formátu ORF.

**Comment by martin1cerny** [comment]
Potvrzuji, tato verze má sloužit pro verzování schématu. Více variant ocenění bych v tuto chvíli nechal jako více samostatných souborů/nabídek. Díky GUID budou takové nabídky plně porovnatelné (jak mezi jednotlivými uchazeči, tak mezi případnými verzemi).

**Comment by kluchLProconom** [comment]
Dobře, díky za info
